<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Scenario: user can login with correct password" tests="4" skipped="0" failures="2" errors="0" timestamp="2017-04-03T12:49:13" hostname="EMANUELA-LENOVO" time="0.033">
  <properties/>
  <testcase name="Given command login is selected" classname="Scenario: user can login with correct password" time="0.002"/>
  <testcase name="When username &quot;pekka&quot; and password &quot;akkep1234&quot; are entered" classname="Scenario: user can login with correct password" time="0.0"/>
  <testcase name="Then system will respond with &quot;logged in&quot;" classname="Scenario: user can login with correct password" time="0.013">
    <failure message="java.lang.AssertionError" type="java.lang.AssertionError">java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at ohtu.Stepdefs.system_will_respond_with(Stepdefs.java:38)
	at ✽.Then system will respond with &quot;logged in&quot;(ohtu/login.feature:6)
</failure>
  </testcase>
  <testcase name="classMethod" classname="Scenario: user can login with correct password" time="0.342">
    <failure message="java.lang.AssertionError" type="java.lang.AssertionError">java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at ohtu.Stepdefs.system_will_respond_with(Stepdefs.java:38)
	at ✽.Then system will respond with &quot;logged in&quot;(ohtu/login.feature:6)
</failure>
  </testcase>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
